### ISSUE TITLE
Don't see blurred text

### ISSUE THREAD

**Issue by G07cha** [garris/BackstopJS#110]
This is how it's looks like on page:

![screen shot 2015-11-03 at 1 51 32 pm](https://cloud.githubusercontent.com/assets/6943514/10907361/06be483e-8232-11e5-9425-1d001c0665f5.png)

This is how it's looks on reports:

![screen shot 2015-11-03 at 1 50 39 pm](https://cloud.githubusercontent.com/assets/6943514/10907362/07937130-8232-11e5-9faf-30e4285a6090.png)

On changing blur levels all tests certainly pass.

```html
<div class="tb-blur blur-1x">blur 1x</div>
<div class="tb-blur blur-2x">blur 2x</div>
```

```css
.blur-1x {
	-webkit-filter: blur(1px);
	-moz-filter: blur(1px);
	-ms-filter: blur(1px);
	-o-filter: blur(1px);
	filter: blur(1px);
}
```
