### ISSUE TITLE
Using the newest Docker BackstopJS image breaks our tests (Jenkins)

### ISSUE THREAD

**Issue by jonathanherdt** [garris/BackstopJS#1156]
Our builds currently break with the newest Docker BackstopJS image, 4.5.0. It breaks with both npm version `4.4.2` and `4.5.0`.

Out of our ~1100 tests, 395 fail. Judging from how the tests fail, it seems like BackstopJS doesn't wait long enough until the content is rendered. Most screenshots are completely white and a few show content which is not completely rendered. Most of the tests that are failing are simple HTML/CSS pages. They load some JavaScript but it does not change the appearance. We also have parts of our pages built with React. With the React components, the "white screenshot" issue happens with a much smaller percentage but it is still there.

The original of the screenshot I'm showing here can be seen here: https://www.static-immobilienscout24.de/fro/core/4.2.3/documentation/html/campaign-box.html#usage

If need be, I could also provide a zip file with the HTML pages and our `backstop.json`.

![Screen Shot 2020-03-02 at 12 31 04](https://user-images.githubusercontent.com/6302908/75672752-b1b22480-5c81-11ea-9536-b671a348cd50.png)

**Comment by garris** [comment]
That doesn't sound good.  This happened when you bumped your version?

**Comment by garris** [comment]
Does the smoke test run for you?  https://github.com/garris/BackstopJS#smoke--feature-tests

**Comment by jonathanherdt** [comment]
We didn't bump it but we had `image: backstopjs/backstopjs` (without a version number) in our `docker-compose.yml`.

**Comment by jonathanherdt** [comment]
I wouldn't know how to run the smoke test in a local installation with a custom `docker-compose.yml`. I tried pointing the script to the correct config file (`node_modules/backstopjs/test/configs/backstop`) but then lots of files are missing.

I also just cloned the BackstopJS repo and ran the smoke tests from there. There, it looked fine.

**Comment by jonathanherdt** [comment]
Also of note: We're using a custom `docker-compose.yml` with the following content:

```yml
version: "2.1"
services:
    testrunner:
        image: backstopjs/backstopjs:4.5.0
        volumes_from:
            - container:${HOSTNAME}:rw
        working_dir: ${WORKSPACE}
        shm_size: 2048m
        command: "test  --config ./src/test/regression/.generated.backstop.json"
```

We're running it with the following command: `docker-compose -f docker-compose.yml run --rm testrunner`
