### ISSUE TITLE
Mismatch errors prevent html_report from caching via CI/CD

### ISSUE THREAD

**Issue by ViperART** [garris/BackstopJS#1220]
Greetings!

I'm trying to include backstop tests into CI (gitlab CI in particular). The idea is to host html report on gitlab pages, which is achieved (in my case) through caching backstop_data folder and then using this cache for hosting gitlab pages in next job.

Here's the job from .gitlab-ci.yml that creates report and caches results:

```
test:  
  stage: test
  image:
    name: backstopjs/backstopjs
    entrypoint: [""]
  script:
    - cd frontend/landings/landing
    - backstop reference
    - backstop test
  artifacts:
    when: always
    paths:
      - frontend/landings/landing/backstop_data
  cache:
    key: backstopData
    paths:
      - frontend/landings/landing/backstop_data
  when: manual
```

And it actually works properly - but only if tests are 100% successful (when all of my tests were successful I was able to see report on pages). But if one of the test cases fails, CLI process exits and cache is never written. Meanwhile, artifacts are working properly, and if I download them I can access HTML report just fine.

If I add fail proofing, such as `backstop reference || echo "test failed"`, bitmaps_reference and bitmaps_test folders make it to the cache, but still no access to html_report.

Is there a way to prevent backstop from killing a job on mismatch error? Or am I going in a wrong direction and there's a better way of hosting report on gitlab pages?
