### ISSUE TITLE
How to test only visible viewport?

### ISSUE THREAD

**Issue by ivnish** [garris/BackstopJS#1508]
I need to test full-screen popup form. Screenshot contains a form and full page. How to test only visible viewport without page scrolling? If viewport is 1920x1080 I want to get screenshot size is 1920x1080 too

**Comment by dgrebb** [comment]
@ivnish did you try using `'viewport'` as a selector? This is covered in the [README's Advanced Scenarios](https://github.com/garris/BackstopJS#advanced-scenarios) section:

`selectors                // Array of selectors to capture. Defaults to document if omitted. Use "viewport" to capture the viewport size.`

**Comment by ivnish** [comment]
Yes. I tried it. 

By default I have full page screenshot

![2023-10-25_17-08](https://github.com/garris/BackstopJS/assets/29428813/a50bb44f-e52d-46da-bbb2-63b94174bf1b)

If I use `const BACKSTOP_TEST_CSS_OVERRIDE = .dialog-off-canvas-main-canvas {height:100vh;overflow:hidden;};`

I have only 1920x1080 site, but I have a lot of space bottom in screenshot file

![2023-10-25_17-09](https://github.com/garris/BackstopJS/assets/29428813/8d8c1140-c562-4be8-bd35-c619d3fc3c63)

I expected:

![2023-10-25_17-09__](https://github.com/garris/BackstopJS/assets/29428813/e5be478d-23f6-4854-953b-d47a5ad6a069)

**Comment by dgrebb** [comment]
Very strange — it looks like `document` is being used as the selector. You may need to set `100vh` on `html` and `body`, as opposed to `.dialog-off-canvas-main-canvas` to get around this. Not ideal, but this has brought be the best success. 

In one of my overrideCSS scripts I have:

```css
  body {
    height: 100% !important;
    min-height: 100% !important;
    position: absolute !important;
    top: 0 !important;
    bottom: 0 !important;
    left: 0 !important;
    right: 0 !important;
  }
```

Which seems crazy, but gets the job done :)

_In my use case I have `overflow: scroll` on `body` for stylistic reasons, so the above override is specific to that._
