### ISSUE TITLE
Running Docker image backstopjs results in Error Error: Cannot find module '/src/backstop.json'

### ISSUE THREAD

**Issue by silentHoo** [garris/BackstopJS#732]
Hi together, first of all thanks for BackstopJS. This really is a time saver.

I've some trouble running the `backstopjs/backstopjs:v3.1.21` image in a Gitlab CI pipeline. Locally it's not a problem, only on Gitlab it seems to be a problem. I just want to post this issue here for others and I've no solution for now - hoping to get more infos with this issue.

I run the following on a Gitlab runner via `.gitlab-ci.yml` (this is only the first iteration to see how it could work - I don't want to setup a full-fledged infrastructure for the webserver):

This only for verbose output to see if the volumes are mounted:

```
docker run --rm --entrypoint "/bin/ls" -v ${PWD}/backstop.json:/src/backstop.json -v ${PWD}/backstop_data/:/src/backstop_data/ backstopjs/backstopjs:v3.1.21 -l
total 8
drwxr-xr-x 2 root root 4096 Apr 13 11:30 backstop.json
drwxr-xr-x 2 root root 4096 Apr 13 11:30 backstop_data
```

And this to run the official `backstopjs/backstopjs` image:

```
$ docker run --rm -v ${PWD}/backstop.json:/src/backstop.json -v ${PWD}/backstop_data/:/src/backstop_data/ backstopjs/backstopjs:v3.1.21 test
BackstopJS v3.1.21
Error Error: Cannot find module '/src/backstop.json'
```

Does anyone had a similar issue? Thank you in advance.

**Comment by garris** [comment]
Thanks for posting.  Hopefully someone can follow up with some insight.   Cheers.

**Comment by Kenith** [comment]
you may try the docker image here: [https://github.com/Kenith/ta-visual-lib](https://github.com/Kenith/ta-visual-lib)

Hope could be the help

**Comment by silentHoo** [comment]
The problem was, that I ran the command 

```
docker run --rm -v ${PWD}/backstop.json:/src/backstop.json -v ${PWD}/backstop_data/:/src/backstop_data/ backstopjs/backstopjs:v3.1.21 test
```

within the `script:` section of the `.gitlab-ci.yml`.

This doesn't work in Gitlab CI. Instead I switched to use `backstopjs/backstopjs` as the base image for my stage and overwrite the entrypoint to start backstop in `script:`:

```
test-visual:
  stage: test
  image:
    name: backstopjs/backstopjs:v3.1.21
    entrypoint: [""]
  script:
    - backstop test
```

So this was not an issue with your docker image, rather than how I configured my `.gitlab-ci.yml`.

**Comment by garris** [comment]
@silentHoo glad it’s working for you.  Thanks for posting your solution!

**Comment by joejoseph00** [comment]
@silentHoo YES, this totally was my issue as well, I also had to substitute the 'backstopjs' command I was previously using with the 'backstop' command as backstopjs does not exist on that docker image but the backstop command does exist.

Here's a snippet of my .gitlab-ci.yml in case it helps others.

```
backstopjs-beta:1.3:
  image:
    name: backstopjs/backstopjs:v3.1.21
    entrypoint: [""]

  before_script:
    - cp /builds/group/myproject/backstopjs_beta /src -pr
    - ls -al /src

  script:
    - pwd
    - cd /src
    - cd backstopjs_beta
    - backstop reference
    - backstop test
#   - cd .. should be the last step here
    - cd ..

  after_script:
    - cp -pr /src/backstopjs_beta/backstop_data/html_report public

  artifacts:
    paths:
    - public
    expire_in: 1 week

```
