### ISSUE TITLE
Viewport (vh) units not working correctly for Backstop

### ISSUE THREAD

**Issue by matthew-dean** [garris/BackstopJS#798]
I have an element with this CSS (simplified):

```css
.component {
  margin-top: 85px;
  height: calc(100vh - 200px);
}
```

My configuration file for backstop has the viewport setting:
```js
{
  // ...
  viewports: [
    {
      label: 'desktop',
      width: 1600,
      height: 800
    }
    // ...
  ]
}
```
So, technically, the component should be a rendered height of 600, if the viewport is truly 800 pixels. But the captured component is actually 2413 pixels tall. Why are all our components that use viewport units so tall?
